### ISSUE TITLE
Multi-regio and multi-populaties data structuur

### ISSUE THREAD

**Issue by LEDfan** [LEDfan/Bachelorproef#109]
- [x] voor elke regio wordt er een implementatie van AbstractPopBuilder class aangemaakt met eigen parameters #139 
     - AbstractPopBuilder is algemene parent lcass boven elke popbuilder
     - vult de Population structuur

 - [x] Population die overeft van SegementedVector
 - [x] Swig aanpassen voor Population
 
 - eventueel kunnen re-allocaties in ContactPoolSys vermeden worden door over te stappen naar SegmentedVector

 - [x] population krijgt een index structuur om bij te houden welke persoon in welke regio zit. Bv om te bepalen wat is het percentage geinfecteerde in regio x"?
    - raw data om de afbakeningen van regios te construeren
    - [x] data structuur -> #136 
    - [x] integratie met bestaande Population -> #139 
    - [x]  Multi pop parallelism + fix for unique contact Pools #140  -> #146

 - [x] RegioSlicer/View: abstractie om vlot met de regionale data om te kunnen gaan (Mapviewer etc): -> #160 
    - overloaded .at, operator[], begin(), end()
    - bv: `slicer[string met regio-naam]` -> sequence van populatie van die regio
          `slicer[contactPoolType::Id]`   -> sequence met alle (over regios heen) pools van type Id
          `slicer[contactPoolType::Id][string met regio-naam]`

 - [x] GeoSlicer/View: abstractie om vlot met geografische data om te kunnen gaan:
    - GeoSlice `slicer[<coordinaten>, <afstand>]` -> "hoeveel geïnfecteerden in een straal van 100km rond Antwerpen?"
    -> [x] #133 
    - GeoSlice `slicer[<coordinaten>, <coordinaten>]`
    - GeoSlice `slicer[<polygoon>]`
    => kd-Tree
    => GeoGrid::InBox(loc1, loc2)
    => GeoGrid::FindLocationsInRadius(start, radius)
    => Boost::Geometry polygon -> bounding box -> InBox -> filter(Boost::Geometry inside)/apply
```
    Collector<T>::operator()(T value)

    template <class <class...> Agg, typename F>
    auto MakeAggregator(F f) -> Agg<F>;

    Aggregator<F>
        -> BoxAggregator
        -> PolygonAggregator
        -> RadiusAggregator
        :: operator() / Aggregate()
        :: Aggregator(F functor)
    Aggregator<>::operator()(Geogrid, const Function& f);
    
    T GeoGrid::BuildAggregator<T, Args...>() {
        return T(this, std::forward(args));
    }

```

 - [ ] TravelerIndeces: datastructuur in de regio om via `push_back/pop` bij te houden wie er in tijdelijk en niet-resident in bepaalde ContactPools verblijft 
    - bij de person wordt aangegeven dat hij afwezig is uit zijn residente Contactpools
    - vertrekdata van bezoekers opnemen
    - live aanpassen in simulatie #110

    > Daarin zijn o.a. de vertrekdata van de bezoekers opgenomen. Ook voor ieder 
	relevant ContactPoolType (bijv. work voor business travel en primary community
	voor toeristen) bij welke ContactPools er bezoekers aanwezig zijn en vanaf welke 
	vector-subscript zij geregistreerd staan. We registreren ze zodanig dat de bezoeker 
	die eerst vertrekt het dichtst bij het einde van de vector zit. Dat impliceert 
	(1) dat een vertrek equivalent is aan een pop op de vector in de ContactPool en 
	(2) een aankomst van een bezoeker betekent dat, als deze een zeer kort verblijfsduur 
	heeft en dus ook de eerste vertrekker wordt, een push_back volstaat. Maar meestal
	zal een partiele herordening van de staart van de vector naar vertrekdatum nodig zijn.
	
    > Een alternatief is om vertrekkers met aankomers te overschrijven en als 
	er meer aankomers zijn die via push_back to te voegen, als er meer vertrekkers zijn
	de staart van de vector "in te trekken" door plaatsen op te schuiven en de finale
	lege plaatsen weg te pop'en.
 
   >  Benevens voorgaande zijn mogelijk extra data members (maar zo weinig mogelijk) bij 
    Person vereist om het geheel te administreren. Dergelijk koppeling zal aan het begin
    van elke tijdstap door de aparte methode uitgevoerd worden.
